version: "3.9"

services:
  arangodb:
    image: arangodb:latest
    container_name: arangodb
    restart: unless-stopped
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps

volumes:
  arangodb_data:
  arangodb_apps:
