ktor:
  application:
    modules:
      - com.example.com.ApplicationKt.module
  deployment:
    port: "$PORT:8080"
    watch:
      - classes

arango:
  host: "$ARANGO_HOST:127.0.0.1"
  port: "$ARANGO_PORT:8529"
  user: "$ARANGO_USER:root"
  password: "$ARANGO_PASSWORD:password"
  db: "$ARANGO_DB:tutorial"
