ktor:
    application:
        modules:
            - com.example.com.ApplicationKt.module
    deployment:
        port: 8080

    arango:
        host: "127.0.0.1"
        host: ${?ARANGO_HOST}

        port: 8529
        port: ${?ARANGO_PORT}

        user: "root"
        user: ${?ARANGO_USER}

        password: "password"
        password: ${?ARANGO_PASSWORD}

        db: "tutorial"
        db: ${?ARANGO_DB}
